### ISSUE TITLE
Perf: club overview page re-renders every time

### ISSUE THREAD

**Issue by Josh-Cena** [Computerization/Enspire#301]
It is common to jump between individual club pages and the club overview page. (e.g. between https://theenspire.com/clubs and https://theenspire.com/clubs/computerization)

There are two problems:
1. Every time we visit another page and go back to the overview, the page re-renders. This is troublesome because: 
    - The state (scroll position, expanded subsections) is not preserved;
    - The connection is rather slow.
2. The images in the collapsed sections should be eagerly rendered as well, because it is frustrating to expand each section and still wait for the images to load.

I think this can be solved by adding `KeepAlive` somewhere. I need further information on what are the requests sent on each load, and which should be cached.

**Comment by qwerzl** [comment]
@Josh-Cena Could we close this issue? We've refactored this project from the ground up.
