### ISSUE TITLE
Logo!

### ISSUE THREAD

**Issue by qwerzl** [Computerization/Enspire#517]
For anyone who has ideas for Enspire's logo, sumbit here.

**Comment by q1zhen** [comment]
![image](https://github.com/Computerization/Enspire/assets/142765265/cae97557-8bf3-47be-9ad5-cae69c90178d)
![image](https://github.com/Computerization/Enspire/assets/142765265/adda21d7-3544-4dff-b228-a814e981fb2f)

Maybe something like this

**Comment by RadioNoiseE** [comment]
![image](https://github.com/Computerization/Enspire/assets/86350742/ebb19392-f955-4a7c-8f44-a9c0df68dfe0)
MF!

**Comment by qwerzl** [comment]
![Untitled](https://github.com/Computerization/Enspire/assets/46770502/b232584c-691c-4078-b097-b4de168bd09f)

![Untitled 3](https://github.com/Computerization/Enspire/assets/46770502/7cc0810b-b963-418a-9806-a91c58b8ac78)

Just choose one plz or if anyone has a better idea post yours here.

**Comment by q1zhen** [comment]
> ![Untitled](https://private-user-images.githubusercontent.com/46770502/311505571-b232584c-691c-4078-b097-b4de168bd09f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzExMTEsIm5iZiI6MTcxMDA3MDgxMSwicGF0aCI6Ii80Njc3MDUwMi8zMTE1MDU1NzEtYjIzMjU4NGMtNjkxYy00MDc4LWIwOTctYjRkZTE2OGJkMDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDExNDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYjg3MDlhZmI5NTdjYTgxYWEwYWQ1NDVmYmVjMTYyYzhmOWNiODk3MGRjZmMxNTMzMjNjMmI3ZGE3NGI4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WN4Dcw5AlrsvqffltFLj9z4_VvDtRdjmnvdUwWE89po)
> 
> ![Untitled 3](https://private-user-images.githubusercontent.com/46770502/311506303-7cc0810b-b963-418a-9806-a91c58b8ac78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzExMTEsIm5iZiI6MTcxMDA3MDgxMSwicGF0aCI6Ii80Njc3MDUwMi8zMTE1MDYzMDMtN2NjMDgxMGItYjk2My00MThhLTk4MDYtYTkxYzU4YjhhYzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDExNDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzFmODMxNmRmZTRmYzM2NDFlNjI4OTU1MTdmNDY1M2Y4YWY2Y2NjY2JhZWExNTRmOWY5NzQwMTBmY2I0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rPqb5hTHl-XfG7sbK_W7mmJM36inq3Brx9OVFojxnxw)
> 
> Just choose one plz or if anyone has a better idea post yours here.

what font is this? is it okay for commercial uses?

**Comment by qwerzl** [comment]
> > ![Untitled](https://private-user-images.githubusercontent.com/46770502/311505571-b232584c-691c-4078-b097-b4de168bd09f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzExMTEsIm5iZiI6MTcxMDA3MDgxMSwicGF0aCI6Ii80Njc3MDUwMi8zMTE1MDU1NzEtYjIzMjU4NGMtNjkxYy00MDc4LWIwOTctYjRkZTE2OGJkMDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDExNDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYjg3MDlhZmI5NTdjYTgxYWEwYWQ1NDVmYmVjMTYyYzhmOWNiODk3MGRjZmMxNTMzMjNjMmI3ZGE3NGI4ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WN4Dcw5AlrsvqffltFLj9z4_VvDtRdjmnvdUwWE89po)
> > ![Untitled 3](https://private-user-images.githubusercontent.com/46770502/311506303-7cc0810b-b963-418a-9806-a91c58b8ac78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzExMTEsIm5iZiI6MTcxMDA3MDgxMSwicGF0aCI6Ii80Njc3MDUwMi8zMTE1MDYzMDMtN2NjMDgxMGItYjk2My00MThhLTk4MDYtYTkxYzU4YjhhYzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDExNDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzFmODMxNmRmZTRmYzM2NDFlNjI4OTU1MTdmNDY1M2Y4YWY2Y2NjY2JhZWExNTRmOWY5NzQwMTBmY2I0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rPqb5hTHl-XfG7sbK_W7mmJM36inq3Brx9OVFojxnxw)
> > Just choose one plz or if anyone has a better idea post yours here.
> 
> what font is this? is it okay for commercial uses?

Well we are not a business so

**Comment by q1zhen** [comment]
better use a free font though, just in case. Roboto, Poppins, and Inter are all quite similar to the one you used.
